- title: Giới thiệu
  posts:
  - 

- title: SublimeText
  url: /dev/sublimetext
  posts:
  - sublimetext/
  - sublimetext/installtion
  - sublimetext/usage

- title: Pascal
  url: /dev/pascal
  posts:
  - pascal/
  - pascal/first_program
  - pascal/basic_syntax
  - pascal/data_types
  - pascal/variable_init
  - pascal/io
  - pascal/conditions
  - pascal/loops
  - pascal/function
  - pascal/procedure
  - pascal/variable_scope
  - pascal/strings
  - pascal/boolean
  - pascal/arrays
  - pascal/records
  - pascal/files
  - pascal/quick_guide

- title: C / C++
  url: /dev/c
  posts:
  - c/
  - c/installation
  - c/sample

- title: C#
  url: /dev/csharp
  posts:
  - csharp/
  - csharp/installation
  - csharp/sample

- title: Javascript
  url: /dev/javascript
  posts:
  - javascript/
  - javascript/installation
  - javascript/sample
