- title: Giới thiệu
  url: 

- title: SublimeText
  url: sublimetext
  posts:
  - url: 
  - url: installtion
  - url: usage

- title: Pascal
  url: pascal
  posts:
  - url: 
  - url: first_program
  - url: basic_syntax
  - url: data_types
  - url: variable_init
  - url: io
  - url: conditions
    posts:
    - url: 
    - url: if
    - url: case
  - url: loops
    posts:
    - url: 
    - url: for
    - url: while
    - url: repeat
  - url: subprogram
    posts:
    - url: 
    - url: function
    - url: procedure
    - url: variable_scope
  - url: data_structures
    posts:
    - url: 
    - url: strings
    - url: boolean
    - url: arrays
    - url: records
  - url: files
  - url: quick_guide

- title: C / C++
  url: c
  posts:
  - url: 
  - url: installation
  - url: sample

- title: C#
  url: csharp
  posts:
  - url: 
  - url: installation
  - url: sample

- title: Javascript
  url: javascript
  posts:
  - url: 
  - url: installation
  - url: sample
